pipeline {
    agent { label 'linux' }
    tools {
        maven 'apache-maven-3.0.5'
    }
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/elenaandries/weather/tree/master/projectFinal'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile'       
            }
        }
    }
}
